"""create conversions table

Revision ID: 5ec5f474cad6
Revises: 
Create Date: 2025-06-25 14:55:12.490432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ec5f474cad6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='statusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('download_url', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversions_file_id'), 'conversions', ['file_id'], unique=True)
    op.create_index(op.f('ix_conversions_file_name'), 'conversions', ['file_name'], unique=False)
    op.create_index(op.f('ix_conversions_id'), 'conversions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversions_id'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_file_name'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_file_id'), table_name='conversions')
    op.drop_table('conversions')
    # ### end Alembic commands ###
